version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    env_file: .env
    ports:
      - "${MYSQL_PORT}:3306"  # map port MySQL ra localhost
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
      
  order-service:
    build: 
      context: ./order-service
      dockerfile: Dockerfile
    working_dir: /workspace/order-service
    container_name: order-service
    ports:
      - "${ORDER_SERVICE_PORT}:8081"  # map port Spring Boot ra localhost
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./order-service:/workspace/order-service
      - ./order-service/pom.xml:/workspace/order-service/pom.xml
      - order-m2:/root/.m2
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/orders?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    command: ["mvn", "spring-boot:run"]

  product-service:
    build: 
      context: ./product-service
      dockerfile: Dockerfile
    working_dir: /workspace/product-service
    container_name: product-service
    ports:
      - "${PRODUCT_SERVICE_PORT}:8082"  # map port Spring Boot ra localhost
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./product-service:/workspace/product-service
      - ./product-service/pom.xml:/workspace/product-service/pom.xml
      - product-m2:/root/.m2
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/products?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    command: ["mvn", "spring-boot:run"]

volumes:
  mysql_data:
  product-m2:
  order-m2:
